platform :ios, '9.0'

target 'MobileAttendance' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MobileAttendance

    pod 'Alamofire'
    pod 'SwiftyJSON'
    pod 'GoogleMaps'
    pod 'GooglePlaces'
    pod 'SideMenu'
    pod 'DatePickerDialog'
    pod 'PickerView'

end
